/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_Java_com_yf_lib_tigerbox_tigertones_NativeHelper
#define _Included_Java_com_yf_lib_tigerbox_tigertones_NativeHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Java_com_yf_lib_tigerbox_tigertones_NativeHelper
 * Method:    open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yf_lib_tigerbox_tigertones_NativeHelper_open
  (JNIEnv *, jobject);

/*
 * Class:     Java_com_yf_lib_tigerbox_tigertones_NativeHelper
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yf_lib_tigerbox_tigertones_NativeHelper_close
  (JNIEnv *, jobject);

/*
 * Class:     Java_com_yf_lib_tigerbox_tigertones_NativeHelper
 * Method:    ioctl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_yf_lib_tigerbox_tigertones_NativeHelper_ioctl
  (JNIEnv *, jobject, jint, jint);


/*
 * Class:     Java_com_yf_lib_tigerbox_tigertones_NativeHelper
 * Method:    read
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_yf_lib_tigerbox_tigertones_NativeHelper_read
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     Java_com_yf_lib_tigerbox_tigertones_NativeHelper
 * Method:    write
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_yf_lib_tigerbox_tigertones_NativeHelper_write
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
